package net.diegozhu.j2ee.ptms.model;

// Generated Apr 9, 2013 10:21:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * BusLine generated by hbm2java
 */
public class BusLine implements java.io.Serializable {

	private BusLineId id;
	private Bus bus;
	private Line line;

	public BusLine() {
	}

	public BusLine(BusLineId id, Bus bus, Line line) {
		this.id = id;
		this.bus = bus;
		this.line = line;
	}

	public BusLineId getId() {
		return this.id;
	}

	public void setId(BusLineId id) {
		this.id = id;
	}

	public Bus getBus() {
		return this.bus;
	}

	public void setBus(Bus bus) {
		this.bus = bus;
	}

	public Line getLine() {
		return this.line;
	}

	public void setLine(Line line) {
		this.line = line;
	}

}
