package net.diegozhu.j2ee.ptms.model;

// Generated Apr 9, 2013 10:21:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Station generated by hbm2java
 */
public class Station implements java.io.Serializable {

	private int id;
	private String name;
	private String createtime;
	private String description;
	private Integer periority;
	private Double locationX;
	private Double locationY;
	private Boolean availble;
	private Set<LineStation> lineStations = new HashSet<LineStation>(0);
	private Set<Events> eventses = new HashSet<Events>(0);

	public Station() {
	}

	public Station(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Station(int id, String name, String createtime, String description,
			Integer periority, Double locationX, Double locationY,
			Boolean availble, Set<LineStation> lineStations,
			Set<Events> eventses) {
		this.id = id;
		this.name = name;
		this.createtime = createtime;
		this.description = description;
		this.periority = periority;
		this.locationX = locationX;
		this.locationY = locationY;
		this.availble = availble;
		this.lineStations = lineStations;
		this.eventses = eventses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getPeriority() {
		return this.periority;
	}

	public void setPeriority(Integer periority) {
		this.periority = periority;
	}

	public Double getLocationX() {
		return this.locationX;
	}

	public void setLocationX(Double locationX) {
		this.locationX = locationX;
	}

	public Double getLocationY() {
		return this.locationY;
	}

	public void setLocationY(Double locationY) {
		this.locationY = locationY;
	}

	public Boolean getAvailble() {
		return this.availble;
	}

	public void setAvailble(Boolean availble) {
		this.availble = availble;
	}

	public Set<LineStation> getLineStations() {
		return this.lineStations;
	}

	public void setLineStations(Set<LineStation> lineStations) {
		this.lineStations = lineStations;
	}

	public Set<Events> getEventses() {
		return this.eventses;
	}

	public void setEventses(Set<Events> eventses) {
		this.eventses = eventses;
	}

}
