package net.diegozhu.j2ee.ptms.model;

// Generated Apr 9, 2013 10:21:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int id;
	private Role role;
	private String name;
	private String createtime;
	private String description;
	private String workid;
	private String personalid;
	private String address;
	private String cellphone;
	private String gender;
	private Date jointime;
	private Date resigntime;
	private Set<Events> eventses = new HashSet<Events>(0);

	public User() {
	}

	public User(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public User(int id, Role role, String name, String createtime,
			String description, String workid, String personalid,
			String address, String cellphone, String gender, Date jointime,
			Date resigntime, Set<Events> eventses) {
		this.id = id;
		this.role = role;
		this.name = name;
		this.createtime = createtime;
		this.description = description;
		this.workid = workid;
		this.personalid = personalid;
		this.address = address;
		this.cellphone = cellphone;
		this.gender = gender;
		this.jointime = jointime;
		this.resigntime = resigntime;
		this.eventses = eventses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getWorkid() {
		return this.workid;
	}

	public void setWorkid(String workid) {
		this.workid = workid;
	}

	public String getPersonalid() {
		return this.personalid;
	}

	public void setPersonalid(String personalid) {
		this.personalid = personalid;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getJointime() {
		return this.jointime;
	}

	public void setJointime(Date jointime) {
		this.jointime = jointime;
	}

	public Date getResigntime() {
		return this.resigntime;
	}

	public void setResigntime(Date resigntime) {
		this.resigntime = resigntime;
	}

	public Set<Events> getEventses() {
		return this.eventses;
	}

	public void setEventses(Set<Events> eventses) {
		this.eventses = eventses;
	}

}
